# Simple workflow for deploying static content to GitHub Pages
name: Deploy Pages

on:
  push:
    paths:
      - '**.rst' #matches zero or more of any character

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . _build/html"
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/